_format_version: "3.0"
consumers:
- keyauth_credentials:
  - key: dfreese-key
  tags:
  - flight-data
  - flights
  username: dfreese
- keyauth_credentials:
  - key: jdoe-key
  tags:
  - flight-data
  - flights
  username: jdoe
- keyauth_credentials:
  - key: jsmith-key
  tags:
  - flight-data
  - flights
  username: jsmith
- keyauth_credentials:
  - key: jsmith1-key
  tags:
  - flight-data
  - flights
  username: jsmith1
services:
- host: 10.68.87.27
  id: 0cef4d36-9c39-5ac2-9d9f-190d8ea8a252
  name: flights-service
  path: /
  plugins: []
  port: 5052
  protocol: http
  routes:
  - id: 7b2dbd94-ec5b-5ae8-b6d5-4c8b16ce0b06
    methods:
    - GET
    name: flights-service_get-flights
    paths:
    - ~/flights$
    plugins: []
    regex_priority: 200
    strip_path: false
    tags:
    - flight-data
    - flights
  - id: 3210c3ed-9976-500d-ac03-07eaac972ad0
    methods:
    - GET
    name: flights-service_get-flight-by-number
    paths:
    - ~/flights/(?<flightnumber>[^#?/]+)$
    plugins: []
    regex_priority: 100
    strip_path: false
    tags:
    - flight-data
    - flights
  - id: 08020aa2-6106-59ec-903a-3459e7cbb629
    methods:
    - GET
    name: flights-service_get-flight-details
    paths:
    - ~/flights/(?<flightnumber>[^#?/]+)/details$
    plugins: []
    regex_priority: 100
    strip_path: false
    tags:
    - flight-data
    - flights
  - id: a5023323-0468-5a77-baf2-13578fec61b0
    methods:
    - GET
    name: flights-service_health_get
    paths:
    - ~/health$
    plugins: []
    regex_priority: 200
    strip_path: false
    tags:
    - flight-data
    - flights
  tags:
  - flight-data
  - flights
upstreams: []
